spring.application.name=T1-FeignGrupo1
server.port=8080

external-api.json-placeholder.url=https://jsonplaceholder.typicode.com
external-api.fake-store.url=https://fakestoreapi.com
external-api.rick-and-morty.url=https://rickandmortyapi.com/api

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=10000
spring.cloud.openfeign.client.config.default.loggerLevel=basic
